### ISSUE TITLE
Memory leaks 

### ISSUE THREAD

**Issue by ay140** [RPDJF/42-philosophers#1]
Nice code bro, just to inform 

you have a memory leaks, Conditional jumps and data race. this is just to inform you in case if you are submitting to avoid losing points.

GOOD LUCK  

[DOCKER]➜  src valgrind ./philosophers 5 800 200 200 2
==374== Memcheck, a memory error detector
==374== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==374== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==374== Command: ./philosophers 5 800 200 200 2
==374== 
0
0
19 1 is thinking
==375== Conditional jump or move depends on uninitialised value(s)
==375==    at 0x10A6F6: philosopher_routine (in /home/vscode/src/philosophers)
==375==    by 0x1093AB: start_processes (in /home/vscode/src/philosophers)
==375==    by 0x1093FA: start_philo (in /home/vscode/src/philosophers)
==375==    by 0x10956B: main (in /home/vscode/src/philosophers)
==375== 
22 1 has taken a fork
0
23 1 has taken a fork
23 1 is eating
0
33 2 is thinking
==376== Conditional jump or move depends on uninitialised value(s)
==376==    at 0x10A6F6: philosopher_routine (in /home/vscode/src/philosophers)
==376==    by 0x1093AB: start_processes (in /home/vscode/src/philosophers)
==376==    by 0x1093FA: start_philo (in /home/vscode/src/philosophers)
==376==    by 0x10956B: main (in /home/vscode/src/philosophers)
==376== 
37 2 has taken a fork
0
37 3 is thinking
==377== Conditional jump or move depends on uninitialised value(s)
==377==    at 0x10A6F6: philosopher_routine (in /home/vscode/src/philosophers)
==377==    by 0x1093AB: start_processes (in /home/vscode/src/philosophers)
==377==    by 0x1093FA: start_philo (in /home/vscode/src/philosophers)
==377==    by 0x10956B: main (in /home/vscode/src/philosophers)
==377== 
41 2 has taken a fork
41 2 is eating
41 3 has taken a fork
49 4 is thinking
==378== Conditional jump or move depends on uninitialised value(s)
==378==    at 0x10A6F6: philosopher_routine (in /home/vscode/src/philosophers)
==378==    by 0x1093AB: start_processes (in /home/vscode/src/philosophers)
==378==    by 0x1093FA: start_philo (in /home/vscode/src/philosophers)
==378==    by 0x10956B: main (in /home/vscode/src/philosophers)
==378== 
65 5 is thinking
==379== Conditional jump or move depends on uninitialised value(s)
==379==    at 0x10A6F6: philosopher_routine (in /home/vscode/src/philosophers)
==379==    by 0x1093AB: start_processes (in /home/vscode/src/philosophers)
==379==    by 0x1093FA: start_philo (in /home/vscode/src/philosophers)
==379==    by 0x10956B: main (in /home/vscode/src/philosophers)
==379== 
224 1 is sleeping
224 3 has taken a fork
224 3 is eating
225 4 has taken a fork
243 4 has taken a fork
243 2 is sleeping
243 4 is eating
244 5 has taken a fork
424 1 is thinking
426 5 has taken a fork
426 5 is eating
426 3 is sleeping
426 1 has taken a fork
443 2 is thinking
443 2 has taken a fork
444 2 has taken a fork
444 2 is eating
444 4 is sleeping
625 3 is thinking
627 1 has taken a fork
627 1 is eating
627 3 has taken a fork
627 5 is sleeping
643 3 has taken a fork
643 3 is eating
644 4 is thinking
644 4 has taken a fork
==376== 
==376== HEAP SUMMARY:
==376==     in use at exit: 1,176 bytes in 22 blocks
==376==   total heap usage: 53 allocs, 31 frees, 2,712 bytes allocated
==376== 
==376== LEAK SUMMARY:
==376==    definitely lost: 0 bytes in 0 blocks
==376==    indirectly lost: 0 bytes in 0 blocks
==376==      possibly lost: 69 bytes in 2 blocks
==376==    still reachable: 1,107 bytes in 20 blocks
==376==         suppressed: 0 bytes in 0 blocks
==376== Rerun with --leak-check=full to see details of leaked memory
==376== 
==376== Use --track-origins=yes to see where uninitialised values come from
==376== For lists of detected and suppressed errors, rerun with: -s
==376== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
826 4 has taken a fork
826 4 is eating
827 5 is thinking
827 5 has taken a fork
==375== 
==375== HEAP SUMMARY:
==375==     in use at exit: 1,176 bytes in 22 blocks
==375==   total heap usage: 53 allocs, 31 frees, 2,712 bytes allocated
==375== 
==375== LEAK SUMMARY:
==375==    definitely lost: 0 bytes in 0 blocks
==375==    indirectly lost: 0 bytes in 0 blocks
==375==      possibly lost: 69 bytes in 2 blocks
==375==    still reachable: 1,107 bytes in 20 blocks
==375==         suppressed: 0 bytes in 0 blocks
==375== Rerun with --leak-check=full to see details of leaked memory
==375== 
==375== Use --track-origins=yes to see where uninitialised values come from
==375== For lists of detected and suppressed errors, rerun with: -s
==375== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
843 5 has taken a fork
843 5 is eating
==377== 
==377== HEAP SUMMARY:
==377==     in use at exit: 1,176 bytes in 22 blocks
==377==   total heap usage: 53 allocs, 31 frees, 2,712 bytes allocated
==377== 
==377== LEAK SUMMARY:
==377==    definitely lost: 0 bytes in 0 blocks
==377==    indirectly lost: 0 bytes in 0 blocks
==377==      possibly lost: 69 bytes in 2 blocks
==377==    still reachable: 1,107 bytes in 20 blocks
==377==         suppressed: 0 bytes in 0 blocks
==377== Rerun with --leak-check=full to see details of leaked memory
==377== 
==377== Use --track-origins=yes to see where uninitialised values come from
==377== For lists of detected and suppressed errors, rerun with: -s
==377== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
==378== 
==378== HEAP SUMMARY:
==378==     in use at exit: 1,176 bytes in 22 blocks
==378==   total heap usage: 53 allocs, 31 frees, 2,712 bytes allocated
==378== 
==378== LEAK SUMMARY:
==378==    definitely lost: 0 bytes in 0 blocks
==378==    indirectly lost: 0 bytes in 0 blocks
==378==      possibly lost: 69 bytes in 2 blocks
==378==    still reachable: 1,107 bytes in 20 blocks
==378==         suppressed: 0 bytes in 0 blocks
==378== Rerun with --leak-check=full to see details of leaked memory
==378== 
==378== Use --track-origins=yes to see where uninitialised values come from
==378== For lists of detected and suppressed errors, rerun with: -s
==378== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
==379== 
==379== HEAP SUMMARY:
==379==     in use at exit: 1,176 bytes in 22 blocks
==379==   total heap usage: 53 allocs, 31 frees, 2,712 bytes allocated
==379== 
==379== LEAK SUMMARY:
==379==    definitely lost: 0 bytes in 0 blocks
==379==    indirectly lost: 0 bytes in 0 blocks
==379==      possibly lost: 69 bytes in 2 blocks
==379==    still reachable: 1,107 bytes in 20 blocks
==379==         suppressed: 0 bytes in 0 blocks
==379== Rerun with --leak-check=full to see details of leaked memory
==379== 
==379== Use --track-origins=yes to see where uninitialised values come from
==379== For lists of detected and suppressed errors, rerun with: -s
==379== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
^[[B^[[Ac^C==374== 
==374== Process terminating with default action of signal 2 (SIGINT)
==374==    at 0x4861454: futex_abstimed_wait_cancelable (futex-internal.h:320)
==374==    by 0x4861454: do_futex_wait.constprop.0 (sem_waitcommon.c:112)
==374==    by 0x4861547: __new_sem_wait_slow.constprop.0 (sem_waitcommon.c:184)
==374==    by 0x10A3BD: hypervisor (in /home/vscode/src/philosophers)
==374==    by 0x1093D2: start_processes (in /home/vscode/src/philosophers)
==374==    by 0x1093FA: start_philo (in /home/vscode/src/philosophers)
==374==    by 0x10956B: main (in /home/vscode/src/philosophers)
==374== 
==374== HEAP SUMMARY:
==374==     in use at exit: 1,176 bytes in 22 blocks
==374==   total heap usage: 53 allocs, 31 frees, 2,712 bytes allocated
==374== 
==374== LEAK SUMMARY:
==374==    definitely lost: 0 bytes in 0 blocks
==374==    indirectly lost: 0 bytes in 0 blocks
==374==      possibly lost: 69 bytes in 2 blocks
==374==    still reachable: 1,107 bytes in 20 blocks
==374==         suppressed: 0 bytes in 0 blocks
==374== Rerun with --leak-check=full to see details of leaked memory
==374== 
==374== For lists of detected and suppressed errors, rerun with: -s
==374== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**Comment by RPDJF** [comment]
Haven't seen this before !

The project wasn't finished yet, I guess I did fix them on the final version, i'll do same tests

Thanks for the report !
